package cql;

/**
 * 
 * Read BNF.txt
 * */
public enum TokenType {
	BOOLEAN("BOOLEAN"), 
	COMMAND("COMMAND"), CQL("CQL"), ITEMNAME("ITEMNAME"), ITEM_NAME_CASE_SENSITIVE(
			"ITEM NAME CASE SENSITIVE"), ITEM_NAME_CASE_INSENSITIVE(
			"ITEM NAME CASE INSENSITIVE"), RESERVED_WORDS("RESERVED WORDS"), RESERVED_WORD(
			"RESERVED WORD"), SELECTOR_ITEM("SELECTOR ITEM"), CHARS("CHARS"), ACESSOR(
			"ACESSOR"), LITERAL("LITERAL"), STRING("STRING"), NUMBER("NUMBER"), CONDITION(
			"CONDITION"), WHERE("WHERE"), CONDITIONS("CONDITIONS"), CONDITION_ITEM(
			"CONDITION ITEM"), JOIN_CONDITION("JOIN CONDITION"), AND("AND"), OR(
			"OR"), SPACES("SPACES"), INPUT_CHARACTER("INPUT CHARACTER"), HEX(
			"HEX"), INJECT("INJECT"), ASTERISK("ASTERISK"), FUNCTION(
			"FUNCTION"), START_PARAMETERS("START PARAMETERS"), END_PARAMETERS(
			"END PARAMETERS"), SINGLE_QUOTED("SINGLE QUOTED"), SELECTOR_BLOCK(
			"SELECTOR BLOCK"), DOUBLE_QUOTED("DOUBLE QUOTED"), INPUT_CHARACTER_EXCEPT_SINGLE(
			"INPUT CHARACTER EXCEPT SINGLE"), INPUT_CHARACTER_EXCEPT_DOUBLE(
			"INPUT CHARACTER EXCEPT DOUBLE"), INSERT_COMMAND("INSERT COMMAND"), OTHER_COMMAND(
			"OTHER COMMAND"), INSERT("INSERT"), VALUES("VALUES"), INTO("INTO"), START_BRACKET(
			"START BRACKET"), END_BRACKET("END BRACKET"), END_BRACE("END BRACE"), ARRAY(
			"ARRAY"), MAP("MAP"), OPTIONAL_PAIR_SYMBOL("OPTIONAL PAIR SYMBOL"),  PROPERTIES(
			"PROPERTIES"), PROPERTY("PROPERTY"), KEY("KEY"), DOUBLE_DOT(
			"DOUBLE DOT"), COMMA("COMMA"), AS("AS"), ALIAS("ALIAS"), FIELD_NAME(
			"FIELD NAME"), DIGIT("DIGIT"), END_CREATE_TABLE("END CREATE TABLE"), DOT_COMMA(
			"DOT COMMA"), START_CREATE_TABLE("START CREATE TABLE"), CREATE(
			"CREATE"), TABLE("TABLE"), CREATE_TABLE_COMMAND(
			"CREATE TABLE COMMAND"), FALSE("FALSE"), SIGN("SIGN"), ABSOLUTE_HEX("ABSOLUTE HEXA"), ARRAY_BRACE(
			"ARRAY BRACE"), ARRAY_BRACKET("ARRAY_BRACKET"), SELECTOR_ITEM_STRICT(
			"SELECTOR ITEM STRICT"), SYMBOL("SYMBOL"), TTL("TTL"), END_USING("END USING"), USING_OPTION(
			"USING OPTION"), END_CREATE_INDEX_COMMAND(
			"END CREATE INDEX COMMAND"), INDEX("INDEX"), START_CREATE_INDEX_COMMAND(
			"START CREATE INDEX COMMAND"), CREATE_INDEX_COMMAND(
			"CREATE INDEX COMMAND"), CREATE_COMMAND("CREATE COMMAND"), HEXA_CHAR(
			"HEXA CHAR"), START_BRACE("START BRACE"),START_HEX("START HEX"), ANY("ANY"), START_TTL(
			"START TTL"), START_USING("START USING"), SET("SET"), FROM("FROM"), END_COMMON_COMMAND(
			"END COMMON OTHER COMMAND"), START_UPDATE_COMMAND(
			"START UPDATE COMMAND"), UPDATE("UPDATE"), DELETE("DELETE"), START_DELETE_COMMAND(
			"START DELETE COMMAND"), UPDATE_COMMAND("UPDATE COMMAND"), DELETE_COMMAND(
			"DELETE COMMAND"), CONDITIONAL_COMMAND("CONDITIONAL COMMAND"), ENTITY_NAME(
			"ENTITY NAME"), TABLE_NAME("TABLE_NAME"), TABLE_NAME_DECLARATION(
			"TABLE NAME DECLARATION"), TRUE("TRUE"),FIELD_NAME_DECLARATION(
			"FIELD NAME DECLARATION"), FIELD_VALUE("FIELD VALUE"), FIELD_LIST(
			"FIELD LIST"), DROP("DROP"), DROP_COMMAND("DROP_COMMAND"), ALLOW(
			"ALLOW"), FILTERING("FILTERING"), USING("USING"), ALLOW_PARAMETER(
			"ALLOW PARAMETER"), TTL_PARAMETER("TTL PARAMETER"), LIMIT_OPTION("LIMIT OPTION"), LIMIT("LIMIT");

	private String name = null;

	TokenType(String name) {
		this.name = name;
	}

	public String getName() {
		return this.name;
	}
}
