package cql;

/**
 * 
 * Ler BNF.txt
 * */
public enum TokenType {
	COMMAND, CQL, ITEMNAME, ITEMNAME_CASE_SENSITIVE, ITEMNAME_CASE_INSENSITIVE, 
	RESERVED_WORDS, RESERVED_WORD, SELECTOR_ITEM, CHARS, ACESSOR, LITERAL, STRING, NUMBER,
	CONDITION, WHERE, CONDITIONS, CONDITION_ITEM, JOIN_CONDITION, AND, OR, COMA, SPACES,INPUT_CHARACTER,
	HEX, SYMBOL, INJECT
}
